//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 USRPDBMFC.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_USRPDBMFC_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_USRPDBMFC_Admin             129
#define IDD_USRPDBMFC_Operator          130
#define IDD_Admin_INSERT                134
#define IDD_Admin_SELECT                137
#define IDD_Admin_PREDICT               138
#define IDD_Operator_SELECT             139
#define IDD_Operator_PREDICT            140
#define IDI_ICON_BADGE                  141
#define IDC_EDIT_LOGINNAME              1000
#define IDC_EDIT_LOGINPWD               1001
#define IDC_BUTTON_LOGIN                1002
#define IDC_STATIC_LOGINNAME            1003
#define IDC_STATIC_LOGINPWD             1004
#define IDC_BUTTON_LOGOUT               1005
#define IDC_TAB_Admin                   1006
#define IDC_AINMATERIAL                 1008
#define IDC_AINSTATICFORCE              1009
#define IDC_BUTTON_ASELECT              1010
#define IDC_AINAMPLITUDE                1011
#define IDC_AINSPACE                    1012
#define IDC_AINVELOCITY                 1013
#define IDC_AINPASSES                   1014
#define IDC_AINORIRS                    1015
#define IDC_AINRS                       1016
#define IDC_AINRA                       1017
#define IDC_AINORIRA                    1018
#define IDC_AINHARDNESS                 1019
#define IDC_AINORIHARDNESS              1020
#define IDC_COMBO1                      1022
#define IDC_APREMaterial                1022
#define IDC_BUTTON_AINSERT              1034
#define IDC_BUTTON_APREDICT             1035
#define IDC_ASELMaterial                1036
#define IDC_ASELSTATICFORCE             1037
#define IDC_ASELVELOCITY                1038
#define IDC_ASELAMPLITUDE               1039
#define IDC_ASELPASSES                  1040
#define IDC_ASELSPACE                   1041
#define IDC_ASELORIRS                   1042
#define IDC_ASELRS                      1043
#define IDC_ASELORIRA                   1044
#define IDC_ASELRA                      1045
#define IDC_ASELORIHARDNESS             1046
#define IDC_ASELHARDNESS                1047
#define IDC_ASELEffRS                   1048
#define IDC_ASELEffRa                   1049
#define IDC_APRESTATICFORCE             1049
#define IDC_ASELEffHardness             1050
#define IDC_APREAMPLITUDE               1050
#define IDC_APRESPACE                   1051
#define IDC_APREVELOCITY                1052
#define IDC_APREPASSES                  1053
#define IDC_APREORIRS                   1054
#define IDC_APRERS                      1055
#define IDC_APREORIRA                   1056
#define IDC_APRERA                      1057
#define IDC_APREORIHARDNESS             1058
#define IDC_APREHARDNESS                1059
#define IDC_APREEffRa                   1060
#define IDC_APREEffHardness             1061
#define IDC_APREEffRS                   1062
#define IDC_ASELTIME                    1063
#define IDC_ASELNAME                    1064
#define IDC_SLIDER_APRESSTATICFORCE     1066
#define IDC_SLIDER_APRESAmplitude       1067
#define IDC_TAB_Operator                1067
#define IDC_OSELMaterial                1068
#define IDC_SLIDER_APRESSpace           1069
#define IDC_OSELTIME                    1069
#define IDC_SLIDER_APRESVelocity        1070
#define IDC_OSELSTATICFORCE             1070
#define IDC_SLIDER_APRESPasses          1071
#define IDC_OSELVELOCITY                1071
#define IDC_OSELAMPLITUDE               1072
#define IDC_OSELPASSES                  1073
#define IDC_OSELSPACE                   1074
#define IDC_OSELORIRS                   1075
#define IDC_OSELRS                      1076
#define IDC_OSELORIRA                   1077
#define IDC_OSELRA                      1078
#define IDC_OSELORIHARDNESS             1079
#define IDC_OSELHARDNESS                1080
#define IDC_OSELEffRS                   1081
#define IDC_OSELEffRa                   1082
#define IDC_OSELEffHardness             1083
#define IDC_BUTTON_OSELECT              1084
#define IDC_OPRESTATICFORCE             1085
#define IDC_OPREVELOCITY                1086
#define IDC_OPREAMPLITUDE               1087
#define IDC_OPREPASSES                  1088
#define IDC_OPRESPACE                   1089
#define IDC_OPREORIRS                   1090
#define IDC_OPRERS                      1091
#define IDC_OPREORIRA                   1092
#define IDC_OPRERA                      1093
#define IDC_OPREORIHARDNESS             1094
#define IDC_OPREHARDNESS                1095
#define IDC_OPREEffRS                   1096
#define IDC_OPREEffRa                   1097
#define IDC_OPREEffHardness             1098
#define IDC_BUTTON_OPREDICT             1099
#define IDC_SLIDER_OPRESSTATICFORCE     1100
#define IDC_SLIDER_OPRESVelocity        1101
#define IDC_SLIDER_OPRESAmplitude       1102
#define IDC_SLIDER_OPRESPasses          1103
#define IDC_SLIDER_OPRESSpace           1104
#define IDC_OPREMaterial                1105
#define IDC_OSELNAME                    1106
#define IDC_BUTTON_Sign                 1107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
